### PR TITLE
Creates LIC14 function

### LINKED ISSUE #20: LIC14
There exists at least one set of three data points, separated by exactly `E_PTS` and `F_PTS` consecutive intervening points, respectively, that are the vertices of a triangle with area greater than AREA1. In addition, there exist three data points (which can be the same or different from the three data points just mentioned) separated by exactly `E_PTS` and `F_PTS` consecutive intervening points, respectively, that are the vertices of a triangle with area less than `AREA2`. Both parts must be true for the LIC to be true. The condition is not met when `NUMPOINTS < 5`.
`0 ≤ AREA2`

### PR DESCRIPTION
**Pull request by BrorSebastianSjovald**
This implements LIC14 functionality and relevant tests. Possible further development could be done on the tests. Right now only one of the conditions are tested when false. Next step would be to test when the other one is false or when both are false.

Closes #20

### CODE REVIEW

**Review by Sefik-Palazoglu — CHANGES_REQUESTED** [review]
```
The condition is not met when
NUMPOINTS <5.
```
Can you also check this beforehand and if NUMPOINTS < 5 return false before doing anything else?

**Comment by BrorSebastianSjovald** [comment]
Added requested change!

**Review by Sefik-Palazoglu — COMMENTED** [review]
Looks Good!

**Review by Sefik-Palazoglu — APPROVED** [review]

**Comment by Sefik-Palazoglu** [comment]
We need to merge this while keeping both changes. Conflict appeared because we edit the same file. We need another reviewer for this I think.

**Review by Sefik-Palazoglu — APPROVED** [review]
I think this does it. Good work!

**Comment by BrorSebastianSjovald** [comment]
The conflict was the two sets of tests for LIC7 and LIC14. They were not interfering with eachother. Git just thought they were conflicting.

**Comment by ludwigjo** [comment]
Looks all good!

**Pull request merged**
