### PR TITLE
Creates slack.yml

### PR DESCRIPTION
**Pull request by amandakrohn**
Action for a bot (pr-bot) to post a slack message in the group slack whenever a PR on main is created.

Code from: https://spacejelly.dev/posts/how-to-use-github-actions-to-automate-tests-and-slack-notifications/

SLACK_BOT_TOKEN must be added under Settings > Secrets by admin.

### CODE REVIEW

**Comment by BrorSebastianSjovald** [comment]
I think @ludwigjo is the Slack admin so he might be able to fix this. 👍

**Comment by darkway-s** [comment]
It works!

**Comment by BrorSebastianSjovald** [comment]
Yee looks good 👍

**Comment by Sefik-Palazoglu** [comment]
I think we need to merge this branch. So our pr-bot in slack will catch other PR's.

**Pull request merged**
