### PR TITLE
Implements LIC2, fixes #4

### LINKED ISSUE #4: LIC2
here exists at least one set of three consecutive data points which form an angle such that:
`angle < (PI − EPSILON)`
or
`angle > (PI + EPSILON)`
The second of the three consecutive points is always the vertex of the angle. If either the first
point or the last point (or both) coincides with the vertex, the angle is undefined and the LIC
is not satisfied by those three points.
`(0 ≤ EPSILON < PI)`

### PR DESCRIPTION
**Pull request by amandakrohn**
Implements LIC2 #4. LIC2 and test are implemented. 

Additional changes :
* Point (hasSameLocation() method added
* ConditionMetVector gets an added constructor that only takes the vector length as parameter. 
* Vector class has a new method length() which returns the length of the vector.

### CODE REVIEW

**Comment by amandakrohn** [comment]
I will fix the merge conflicts.

**Comment by amandakrohn** [comment]
Conflicts fixed

**Review by ludwigjo — APPROVED** [review]
Looks good! The changes with the parameters as argumets makes the testing a lot more intuitive.

**Review by BrorSebastianSjovald — APPROVED** [review]
I agree changing the parameters, making ParameterManager optional greatly simplifies the testing! Good work

**Pull request merged**
