### PR TITLE
fix #2, half test

### LINKED ISSUE #2: LIC0
There exists at least one set of two consecutive data points that are a distance greater than
the length, `LENGTH1`, apart.
`(0 ≤ LENGTH1)`

### PR DESCRIPTION
**Pull request by darkway-s**
fix #2
create a simple unit test
improve small parts of ConidtionsMetVector class and ParameterManager class

### CODE REVIEW

**Comment by Sefik-Palazoglu** [comment]
I have another approach for implementing the constructor:

1. Get the path to input file as the only parameter.
2. Then populate the class's fields while reading from that file.

**Comment by Sefik-Palazoglu** [comment]
Also, I suggest you do one thing in one commit. For example in this single commit, you have made changes including:

- Implement LIC0. (This is relevant for #2)
- Implement LIC0 test. (This is also relevant for #2)
- First two could have been made into two separate commits in the same PR.
- Implement ParameterManager constructor. (I don't see the relevancy to #2 here. Maybe this should have been a different PR.)

**Comment by Sefik-Palazoglu** [comment]
> Also, I suggest you do one thing in one commit. For example in this single commit, you have made changes including:
> 
> * Implement LIC0. (This is relevant for [LIC0 #2](https://github.com/darkway-s/SE-Group10/issues/2))
> * Implement LIC0 test. (This is also relevant for [LIC0 #2](https://github.com/darkway-s/SE-Group10/issues/2))
> * First two could have been made into two separate commits in the same PR.
> * Implement ParameterManager constructor. (I don't see the relevancy to [LIC0 #2](https://github.com/darkway-s/SE-Group10/issues/2) here. Maybe this should have been a different PR.)

If 1. and 2. points do not depend on your ParameterManager implementation. I suggest you don't commit that part and maybe we can work on ParameterManager on a different branch.

**Comment by darkway-s** [comment]
Thanks for your suggestion! I will create a new branch on the latest release part.

**Comment by Sefik-Palazoglu** [comment]
> Thanks for your suggestion! I will create a new branch on the latest release part.

you can edit in issue/22 branch the changes you make about ParameterManager class. I am working on it now.

**Pull request merged**
