### PR TITLE
implement Final unlocking vector class , feat Issue/16 #16

### PR DESCRIPTION
**Pull request by darkway-s**
The Final Unlocking Vector (FUV) is generated from the Preliminary Unlocking Matrix. The input PUV indicates whether the corresponding LIC is to be considered as a factor in signaling interceptor launch. FUV[i] should be set to true if PUV[i] is false (indicating that the associated LIC should not hold back launch) or if all elements in PUM row i are true.
The FUV now will be computed out immediately after initialization.

### CODE REVIEW

**Comment by BrorSebastianSjovald** [comment]
I would recommend changing the constructor or adding another one that takes in the PUV and PUM directly as Vector and Matrix. This makes it easier to test.

Do you have plans to test in another PR?

**Review by amandakrohn — APPROVED** [review]
LGTM! Good job!
Edit: I agree with @BrorSebastianSjovald

**Comment by darkway-s** [comment]
Yes. Maybe we can get some more test-friendly functions in later commits.

**Comment by Sefik-Palazoglu** [comment]
> Yes. Maybe we can get some more test-friendly functions in later commits.

OK, that means we can merge this right?

**Review by Sefik-Palazoglu — APPROVED** [review]
Need to add test friendly functions, but we can do it later. This is merge-ready.

**Comment by BrorSebastianSjovald** [comment]
The `isRowAllTrue()` function could be moved to a more general function in the Matrix class.

Like instead it could be:

```
public boolean isWholeRowEqualTo(int row, T value) {
        Boolean result = true
        for (int i = 0; i < cols; i++) {
            if (pum.getValue(row, i) == T) {
                result = false;
            }
        }
        return result;
}
```

**Comment by darkway-s** [comment]
> The `isRowAllTrue()` function could be moved to a more general function in the Matrix class.
> 
> Like instead it could be:
> 
> ```
> public boolean isWholeRowEqualTo(int row, T value) {
>         Boolean result = true
>         for (int i = 0; i < cols; i++) {
>             if (pum.getValue(row, i) == T) {
>                 result = false;
>             }
>         }
>         return result;
> }
> ```

Yes. Then it would be easier to build universal consturctor which receives input of matrix and vector.
You can open an issue about this.

**Pull request merged**
