### PR TITLE
Implemented the Matrix class, fix #39

### LINKED ISSUE #39: Matrix class
Setup a Matrix class with methods as specified in class diagram

### PR DESCRIPTION
**Pull request by ludwigjo**
Implemented the Matrix class to work with generic type T. Also created some test but I suggest that more test are created later on.

### CODE REVIEW

**Comment by amandakrohn** [comment]
The structure and tests look good! 

I would like to have some functions that can get a specific row (I think that in some calculations of the FUV or PUM a whole row from a matrix is needed). It would also be good to rename getRows and getCols to getRowLength and getColLength (or something similar) since the name getRows and getCols are a bit ambiguous.

**Comment by ludwigjo** [comment]
@amandakrohn Valid suggestions! I'll add that functionality and update the names

**Comment by BrorSebastianSjovald** [comment]
The class and tests look good!

A change I would suggest would be to use a @beforeEach for the test cases as the all require the same setup.

**Comment by ludwigjo** [comment]
@BrorSebastianSjovald Good point to make the tests more clear! Will add that.

**Comment by amandakrohn** [comment]
Looks good! I will merge!

**Comment by darkway-s** [comment]
Great!

**Pull request merged**
